version: "3"

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.12
    networks:
      - default
    hostname: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./conf:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: always

  ring-mqtt:
    container_name: ring-mqtt
    image: tsightler/ring-mqtt
    networks:
      - default
    ports:
      - 8554:8554
    volumes:
      - .:/data
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: "3"
    depends_on:
      - mosquitto

  spring:
    container_name: spring
    depends_on:
      ring-mqtt:
        condition: service_started
    restart: unless-stopped
    build:
      context: $PWD
      dockerfile: Dockerfile.prod
    env_file:
      - $PWD/.envs
    networks:
      - default

networks:
  default: